spring.datasource.url=jdbc:mysql://localhost:3306/ppooii
spring.datasource.username=root
spring.datasource.password=123

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

#none: Hibernate no realiza ninguna operación en el esquema de la base de datos. Debes asegurarte de que el esquema de la base de datos ya exista y sea compatible con tus entidades de Hibernate.
#create: Hibernate crea un nuevo esquema de base de datos cada vez que arranca la aplicación. Esto significa que todas las tablas se crearán desde cero y los datos existentes se perderán. Esta opción es útil durante el desarrollo para crear rápidamente un esquema de base de datos inicial.
#create-drop: Similar a create, pero Hibernate eliminará el esquema de la base de datos cuando se cierre la sesión de la fábrica de sesiones (session factory), es decir, al apagar la aplicación. Esta opción también es útil durante el desarrollo para limpiar la base de datos entre las ejecuciones de la aplicación.
#update: Hibernate actualiza el esquema de la base de datos según las diferencias detectadas entre el modelo de datos de tus entidades y el esquema de la base de datos existente. Se pueden agregar nuevas tablas, columnas o restricciones, pero Hibernate no eliminará ni modificará las tablas o columnas existentes. Esta opción es útil en ambientes de desarrollo y pruebas donde se necesita una forma de mantener el esquema de la base de datos sincronizado con el modelo de datos.
#validate: Hibernate valida el esquema de la base de datos con el modelo de datos de tus entidades, pero no realiza ninguna modificación en el esquema. Si hay alguna discrepancia entre el esquema y el modelo de datos, Hibernate lanzará una excepción durante el inicio de la aplicación. Esta opción es útil en ambientes de producción para garantizar la integridad del esquema de la base de datos.

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.data.jpa.repositories.enabled=true


#true, Spring Boot automáticamente registra un filtro que mantiene abierta la sesión de JPA durante toda la duración de la solicitud HTTP. puede llevar a problemas de rendimiento y a potenciales problemas de "LazyInitializationException", especialmente en aplicaciones grandes o con grandes volúmenes de datos.

#false = JPA se cierra después de que la solicitud ha sido manejada por el controlador, lo que puede mejorar el rendimiento y evitar problemas asociados con la carga diferida (lazy loading) de entidades JPA.